version: '3'

services:
  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  redis:
    image: redis:alpine

  vote:
    image: dockersamples/examplevotingapp_vote:before
    ports:
      - 5000:80
    environment:
      - REDIS_HOST=redis

  result:
    image: dockersamples/examplevotingapp_result:before
    ports:
      - 5001:80
    environment:
      - DB_HOST=db

volumes:
  db-data:
